### ISSUE TITLE
Galleon cant open my wallet

### ISSUE THREAD

**Issue by fhalaseeri** [Cryptonomic/Tezori#351] opened 2018-08-26 21:15 UTC
Hello there,

when i open my wallet in Galleon its comes empty page, can someone help me with this issue ?

Thanks
![galleon](https://user-images.githubusercontent.com/42722911/44633045-430a5180-a98e-11e8-9d9e-57fc578c9d18.JPG)

**Comment by umurb** [comment] 2018-08-27 16:03
Hi,

You are using Windows, am I right? What is the version you are using?
Can you please make sure that your system is up to date and no firewall is blocking the app?

**Comment by umurb** [comment] 2018-09-04 17:13
@fhalaseeri confirmed that it was due to firewall settings. Issue solved. Closing

**Closed by umurb** 2018-09-04 17:13 UTC
