### ISSUE TITLE
Application should attempt to open the last used wallet by default

### ISSUE THREAD

**Issue by murbard** [Cryptonomic/Tezori#336] opened 2018-08-18 13:37 UTC
By default the application should select the last wallet that was used and prompt for the password (unless of course no wallet has been used previously).

An option can let the user select or create a different wallet, but it would be better

**Comment by yourcodesucks** [comment] 2018-08-19 15:52
Duplicate of https://github.com/Cryptonomic/Tezori/issues/337, on plan for R3.

**Closed by yourcodesucks** 2018-08-19 15:52 UTC
