### ISSUE TITLE
Application becomes unresponsive after switching Tezos node

### ISSUE THREAD

**Issue by murbard** [Cryptonomic/Tezori#335] opened 2018-08-18 13:35 UTC
Got to settings, switch the Tezos node, the screen becomes bank and the only option is to quit the app.

**Comment by Sm00g15** [comment] 2018-09-12 01:54
I wasn't able to reproduce this bug, seems to be fixed.

**Comment by anonymoussprocket** [comment] 2019-06-28 23:17
Closing as it doesn't appear to be a persistent issue.

**Closed by anonymoussprocket** 2019-06-28 23:17 UTC
Labels: bug
