### ISSUE TITLE
Cant login into my wallet with my password

### ISSUE THREAD

**Issue by hananyariv** [Cryptonomic/Tezori#475] opened 2018-11-15 05:30 UTC
I keep getting wrong Wallet and password combination error - i am 100% sure that my password is correct .. i had this before and then it magically opened after a few tries - is there a bug ? how can i login otherwise ?!

**Comment by umurb** [comment] 2018-11-15 17:16
There are no bugs with wallet/password combinations. Is it possible that when you generated your password you had your caps lock on or you were using your keyboard with another language layout? You can maybe try to enter your password with caps on or whilst in another language.

Closing this issue as it is not caused by the code.

**Closed by umurb** 2018-11-15 17:16 UTC
