### ISSUE TITLE
"Retrieving your account" in v0.2.0b spins indefinitely when trying to open an empty account created in v0.1.0b

### ISSUE THREAD

**Issue by murbard** [Cryptonomic/Tezori#342] opened 2018-08-20 08:35 UTC
It's counter-intuitive that what the software is waiting for, in an infinite loop, is for a balance to appear. It would be much more natural to show a balance of 0 for a non existing account.

**Comment by umurb** [comment] 2018-08-21 17:18
@murbard I was not able to reproduce this issue. Can you kindly share the steps?

Here is what I tried;
1. Created a new wallet file
2. Created a new account from mnemonic
3. Didn't send any funds to the new manager address. (Empty account but also inactive)

4. Restarted the wallet app
5. Opened above-mentioned wallet file. The wallet didn't hang

6. Restarted the wallet app
7. Created a new wallet file
8. Tried restoring from mnemonic
9. 'The account does not exist'

**Comment by baketzforme** [comment] 2018-08-23 21:04
I got the same thing in v0.2.0b.

1. Upgraded from 0.1.0b to 0.2.0b.
2. Opened previously created (in 0.1.0b), but unused wallet file (with 0 balance and no transaction history)
3. Spinning icon spins forever
4. Can't do anything while it spins

Downgraded to v0.1.0b and it works fine.

**Comment by umurb** [comment] 2018-08-23 21:26
Thank you, @baketzforme I was able to reproduce. I think it has something to do with the persisting states we developed in the second release. 

@yanivkalfa should be able to find the root cause and find a solution. Steps for reproduction is in the previous comment ^^

**Comment by anonymoussprocket** [comment] 2019-06-28 23:16
Closing, doesn't appear to be an ongoing issue.

**Closed by anonymoussprocket** 2019-06-28 23:16 UTC
Labels: bug
