### ISSUE TITLE
Allow seed words to be used multiple times in Import from Mnemonic scene

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#333] opened 2018-08-17 20:31 UTC
I have noticed that the same word can be used two times in a mnemonic, whereas I requested @developer0623 to remove the already used words from autocomplete list. Please roll back this feature and **do not remove a word from the autocomplete list**

Here is the mnemonic for the last account I got from the mnemonic:

![screen shot 2018-08-17 at 4 31 00 pm](https://user-images.githubusercontent.com/37525692/44287481-04142780-a23b-11e8-965d-0f06449aa9e3.png)

**Comment by murbard** [comment] 2018-08-17 20:43
Duplicate of #332

**Closed** 2018-08-17 20:45 UTC
Labels: bug
